// <auto-generated />
using System;
using Infraestructura.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Context.Entidades.ConfiguracionesAgg.Configuraciones", b =>
                {
                    b.Property<string>("ConfiguracionId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ConfiguracionId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("DescripcionTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTransaccion");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaTransaccion");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ModificadoPor");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<Guid>("TransaccionUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransaccionUId");

                    b.HasKey("ConfiguracionId");

                    b.ToTable("Configuraciones", "comunes");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.ConfiguracionesAgg.ConfiguracionesDetalle", b =>
                {
                    b.Property<string>("ConfiguracionId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ConfiguracionId");

                    b.Property<string>("Atributo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Atributo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("DescripcionTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTransaccion");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaTransaccion");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ModificadoPor");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<Guid>("TransaccionUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransaccionUId");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Valor");

                    b.HasKey("ConfiguracionId", "Atributo");

                    b.ToTable("ConfiguracionesDetalle", "Comunes");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Pantalla", b =>
                {
                    b.Property<string>("PantallaId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PantallaId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("DescripcionTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTransaccion");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaTransaccion");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ModificadoPor");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<Guid>("TransaccionUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransaccionUId");

                    b.HasKey("PantallaId");

                    b.ToTable("Pantalla", "Seguridad");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Permisos", b =>
                {
                    b.Property<string>("RolId")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("RolId");

                    b.Property<string>("PantallaId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PantallaId");

                    b.Property<string>("DescripcionTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTransaccion");

                    b.Property<bool>("Editar")
                        .HasColumnType("bit")
                        .HasColumnName("Editar");

                    b.Property<bool>("Eliminar")
                        .HasColumnType("bit")
                        .HasColumnName("Eliminar");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaTransaccion");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ModificadoPor");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<Guid>("TransaccionUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransaccionUId");

                    b.Property<bool>("Ver")
                        .HasColumnType("bit")
                        .HasColumnName("Ver");

                    b.HasKey("RolId", "PantallaId");

                    b.ToTable("Permisos", "Seguridad");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Rol", b =>
                {
                    b.Property<string>("RolId")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("RolId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("DescripcionTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTransaccion");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaTransaccion");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ModificadoPor");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<Guid>("TransaccionUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransaccionUId");

                    b.HasKey("RolId");

                    b.ToTable("Rol", "Seguridad");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("UsuarioId");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Contrasena");

                    b.Property<string>("DescripcionTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTransaccion");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaTransaccion");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("RolId");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("RowVersion");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<Guid>("TransaccionUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TransaccionUId");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", "Seguridad");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.ConfiguracionesAgg.ConfiguracionesDetalle", b =>
                {
                    b.HasOne("Dominio.Context.Entidades.ConfiguracionesAgg.Configuraciones", "Configuraciones")
                        .WithMany("ConfiguracionesDetalle")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuraciones");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Permisos", b =>
                {
                    b.HasOne("Dominio.Context.Entidades.Seguridad.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Usuario", b =>
                {
                    b.HasOne("Dominio.Context.Entidades.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.ConfiguracionesAgg.Configuraciones", b =>
                {
                    b.Navigation("ConfiguracionesDetalle");
                });

            modelBuilder.Entity("Dominio.Context.Entidades.Seguridad.Rol", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
